version: '3'

networks:
  external_network:
  internal_network:
    internal: true

services:

###########
# TRAEFIK #
###########
  traefik:
    image: traefik:2.2
    restart: unless-stopped
    command: 
      #- "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=$ADMIN_EMAIL"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"
      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`traefik.${TOP_DOMAIN}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.middlewares=dashboardauth"
      - "traefik.http.middlewares.dashboardauth.basicauth.users=${TRAEFIK_USERNAME}:${TRAEFIK_PASSWORD}"
    networks:
      - external_network


##########
# CODIMD #
##########
  codi-db:
    # Don't upgrade PostgreSQL by simply changing the version number
    # You need to migrate the Database to the new PostgreSQL version
    image: postgres:9.6-alpine
    restart: unless-stopped
    #mem_limit: 256mb         # version 2 only
    #memswap_limit: 512mb     # version 2 only
    #read_only: true          # not supported in swarm mode please enable along with tmpfs
    #tmpfs:
    #  - /run/postgresql:size=512K
    #  - /tmp:size=256K
    environment:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=codimdpass
      - POSTGRES_DB=codimd
    volumes:
      - ./data/codi/postgres:/var/lib/postgresql/data
    networks:
      - internal_network

  codi-web:
    image: quay.io/codimd/server:1.3.2
    restart: unless-stopped
    #mem_limit: 256mb         # version 2 only
    #memswap_limit: 512mb     # version 2 only
    #read_only: true          # not supported in swarm mode, enable along with tmpfs
    #tmpfs:
    #  - /tmp:size=512K
    #  - /codimd/tmp:size=1M
    volumes:
      - ./data/codi/uploads:/codimd/public/uploads
    environment:
      CMD_DB_URL: postgres://codimd:codimdpass@codi-db:5432/codimd
      CMD_FORBIDDEN_NOTE_IDS: robots.txt
      CMD_IMAGE_UPLOAD_TYPE: filesystem
      CMD_PORT: 80
      CMD_DOMAIN: codimd.${TOP_DOMAIN}
      CMD_PROTOCOL_USESSL: "true"
      CMD_USECDN: "false"
      CMD_URL_ADDPORT: "false"
      CMD_EMAIL: "false"
      CMD_ALLOW_EMAIL_REGISTER: "false"
      CMD_ALLOW_GRAVATAR: "false"
      CMD_ALLOW_FREEURL: "true"
    depends_on:
      - codi-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.codi-web.rule=Host(`codimd.${TOP_DOMAIN}`)"
      - "traefik.http.routers.codi-web.entrypoints=websecure"
      - "traefik.http.routers.codi-web.tls.certresolver=letsencrypt"
      - "traefik.http.services.codi-web.loadbalancer.server.port=80"
    networks:
      - external_network
      - internal_network


#####################
# MASTODON/HOMETOWN #
#####################
  town-db:
    restart: unless-stopped
    image: postgres:9.6-alpine
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    volumes:
      - ./data/hometown/postgres:/var/lib/postgresql/data
    environment:
      # Disable authentication  https://www.postgresql.org/docs/current/auth-trust.html
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - internal_network

  town-redis:
    restart: unless-stopped
    image: redis:5.0-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - ./data/hometown/redis:/data
    networks:
      - internal_network

  town-web:
    image: docker.pkg.github.com/queerhaus/hometown/hometown:master
    restart: unless-stopped
    env_file: .env.hometown
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:3000/health || exit 1"]
    expose:
      - "3000"
    depends_on:
      - town-db
      - town-redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.town-web.rule=Host(`${TOP_DOMAIN}`)"
      - "traefik.http.routers.town-web.entrypoints=websecure"
      - "traefik.http.routers.town-web.tls.certresolver=letsencrypt"
    volumes:
      - ${HOMETOWN_SYSTEM_MOUNTPOINT:-./data/hometown/public/system}:/mastodon/public/system
    networks:
      - external_network
      - internal_network

  town-streaming:
    image: docker.pkg.github.com/queerhaus/hometown/hometown:master
    restart: unless-stopped
    env_file: .env.hometown
    command: node ./streaming
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1"]
    expose:
      - "4000"
    depends_on:
      - town-db
      - town-redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.town-streaming.rule=(Host(`${TOP_DOMAIN}`) && PathPrefix(`/api/v1/streaming`))"
      - "traefik.http.routers.town-streaming.entrypoints=websecure"
      - "traefik.http.routers.town-streaming.tls.certresolver=letsencrypt"
      - "traefik.http.services.town-streaming.loadbalancer.server.port=4000"
    networks:
      - external_network
      - internal_network

  town-sidekiq:
    image: docker.pkg.github.com/queerhaus/hometown/hometown:master
    restart: unless-stopped
    env_file: .env.hometown
    command: bundle exec sidekiq
    depends_on:
      - town-db
      - town-redis
    volumes:
      - ${HOMETOWN_SYSTEM_MOUNTPOINT:-./data/hometown/public/system}:/mastodon/public/system
    networks:
      - external_network
      - internal_network


#############
# NEXTCLOUD #
#############
  nextcloud-db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - ./data/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - internal_network

  nextcloud-app:
    image: nextcloud
    depends_on:
      - nextcloud-db
      - traefik
    volumes:
      - ./data/nextcloud/app:/var/www/html
    environment:
      MYSQL_HOST: nextcloud-db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${NEXTCLOUD_MYSQL_PASSWORD}
      APACHE_DISABLE_REWRITE_IP: 1
      TRUSTED_PROXIES: traefik
      NEXTCLOUD_TRUSTED_DOMAINS: cloud.${TOP_DOMAIN}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.${TOP_DOMAIN}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.nextcloud-headers.headers.stsseconds=15552000"
      - "traefik.http.middlewares.nextcloud-redirect.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-redirect.redirectregex.replacement=https://$${1}/remote.php/dav/"
      - "traefik.http.middlewares.nextcloud-redirect.redirectregex.permanent=true"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-redirect@docker,nextcloud-headers@docker"
    networks:
      - external_network
      - internal_network
