---

- name: Copy common files to localhost
  hosts: 
    - hometown_host
    - collab_host
  tags: 
    - common
  tasks:
  - name: Stop all containers
    command:
      cmd: docker-compose stop
      chdir: /opt/queerhaus/common

  - name: Make a copy of the data
    become: yes
    synchronize:
      src: /opt/queerhaus/common/data/
      dest: /opt/queerhaus/common/data_copy/
      delete: yes
    delegate_to: "{{ inventory_hostname }}"

  - name: Start all containers again for minimum downtime
    command:
      cmd: docker-compose up -d
      chdir: /opt/queerhaus/common

  - name: Change ownership of data dir
    become: yes
    file:
      path: /opt/queerhaus/common/data_copy/
      state: directory
      recurse: yes
      owner: "{{ ansible_user }}"
      group: queers

  - name: Create local dir
    file:
      path: "backup/common/{{ inventory_hostname }}"
      state: directory
      recurse: yes
    delegate_to: localhost

  - name: Download the data
    synchronize:
      mode: pull
      src: /opt/queerhaus/common/data_copy/
      dest: "backup/common/{{ inventory_hostname }}"
      delete: yes


- name: Copy hometown database and files to localhost
  hosts: hometown_host
  tags: hometown
  tasks:
  - name: Stop all containers
    command:
      cmd: docker-compose stop
      chdir: /opt/queerhaus/hometown

  - name: Make a copy of the data
    become: yes
    synchronize:
      src: /opt/queerhaus/hometown/data/
      dest: /opt/queerhaus/hometown/data_copy/
      delete: yes
    delegate_to: "{{ inventory_hostname }}"

  - name: Start all containers again for minimum downtime
    command:
      cmd: docker-compose up -d
      chdir: /opt/queerhaus/hometown

  - name: Change ownership of data dir
    become: yes
    file:
      path: /opt/queerhaus/hometown/data_copy/
      state: directory
      recurse: yes
      owner: "{{ ansible_user }}"
      group: queers

  - name: Create local dir
    file:
      path: backup/hometown/
      state: directory
      recurse: yes
    delegate_to: localhost

  - name: Download the data
    synchronize:
      mode: pull
      src: /opt/queerhaus/hometown/data_copy/
      dest: backup/hometown/
      delete: yes


- name: Copy codimd database and files to localhost
  hosts: collab_host
  tags: codimd
  tasks:

  - name: Stop all containers
    command:
      cmd: docker-compose stop
      chdir: /opt/queerhaus/codimd

  - name: Make a copy of the data
    become: yes
    synchronize:
      src: /opt/queerhaus/codimd/data/
      dest: /opt/queerhaus/codimd/data_copy/
      delete: yes
    delegate_to: "{{ inventory_hostname }}"

  - name: Start all containers again
    command:
      cmd: docker-compose up -d
      chdir: /opt/queerhaus/codimd

  - name: Change ownership of data dir
    become: yes
    file:
      path: /opt/queerhaus/codimd/data_copy/
      state: directory
      recurse: yes
      owner: "{{ ansible_user }}"
      group: queers

  - name: Create local dir
    file:
      path: backup/codimd/
      state: directory
      recurse: yes
    delegate_to: localhost

  - name: Download the data
    synchronize:
      mode: pull
      src: /opt/queerhaus/codimd/data_copy/
      dest: backup/codimd/
      delete: yes


# - name: Copy nextcloud database and files to localhost
#   hosts: collab_host
#   tags: nextcloud
#   tasks:

#   - name: Stop all containers
#     command:
#       cmd: docker-compose stop
#       chdir: /opt/queerhaus/nextcloud

#   - name: Make a copy of the usual data dir
#     become: yes
#     synchronize:
#       src: /opt/queerhaus/nextcloud/data/app
#       dest: /opt/queerhaus/nextcloud/data_copy/
#       delete: yes
#     delegate_to: "{{ inventory_hostname }}"

#   - name: Make a copy of the volume data dir
#     become: yes
#     synchronize:
#       src: "{{ nextcloud_config.app_mountpoint }}"
#       dest: /opt/queerhaus/nextcloud/data_copy/
#       delete: yes
#     delegate_to: "{{ inventory_hostname }}"

#   - name: Start all containers again
#     command:
#       cmd: docker-compose up -d
#       chdir: /opt/queerhaus/nextcloud

#   - name: Change ownership of data dir
#     become: yes
#     file:
#       path: /opt/queerhaus/nextcloud/data_copy/
#       state: directory
#       recurse: yes
#       owner: "{{ ansible_user }}"
#       group: queers

#   - name: Download the data
#     synchronize:
#       mode: pull
#       src: /opt/queerhaus/nextcloud/data_copy/
#       dest: backup/nextcloud/
#       delete: yes
