---

- name: Set up SSH service and users
  hosts: all
  tags: basic
  gather_facts: false
  roles:
    - basic

- name: Set up floating IPs
  hosts: floating_ip
  tags: common
  roles:
    - floating_ip

- name: Install docker and traefik
  hosts: all
  tags: 
    - common
  roles:
    - common
    - traefik

- name: Set up hometown host
  hosts: hometown_host
  tags: hometown
  roles:
    - hometown
    - collective

- name: Set up collab host
  hosts: collab_host
  tags: 
    - collab
    - codimd
    - nextcloud
  roles:
    - codimd
    - nextcloud