---

- name: Set up SSH service and users
  hosts: all
  tags:
    - basic
  gather_facts: false
  roles:
    - basic

- name: Set up floating IPs
  hosts: floating_ip
  tags:
    - basic
  roles:
    - floating_ip

- name: Install docker
  hosts: all
  tags:
    - basic
  roles:
    - docker

- name: Install traefik
  hosts: all
  tags:
    - traefik
  roles:
    - traefik

- name: Set up collective website
  hosts: main_host
  tags:
    - collective
  roles:
     - role: collective
       when: setups.collective is defined

# - name: Set up mobilizon
#   hosts: main_host
#   tags:
#     - mobilizon
#   roles:
#      - role: mobilizon
#        when: setups.mobilizon is defined
