---

- name: Set up SSH service and users
  hosts: all
  tags: basic
  gather_facts: false
  roles:
    - basic

- name: Set up floating IPs
  hosts: floating_ip
  tags: common
  roles:
    - floating_ip

- name: Install docker
  hosts: all
  tags: 
    - common
  roles:
    - common

- name: Install traefik
  hosts: all
  tags: 
    - traefik
  roles:
    - traefik

- name: Set up hometown
  hosts: hometown_host
  tags: 
    - hometown
  roles:
    - hometown

- name: Set up collective website
  hosts: hometown_host
  tags: 
    - collective
  roles:
    - collective

- name: Set up mobilizon
  hosts: hometown_host
  tags: 
    - mobilizon
  roles:
    - mobilizon

- name: Set up collab host
  hosts: collab_host
  tags: 
    - collab
    - codimd
    - nextcloud
  roles:
    - codimd
    - nextcloud

- name: Set up matrix
  hosts: collab_host
  tags: 
    - matrix
  roles:
    - matrix
