---

# - name: Install cronjob
#   become: yes
#   copy:
#     src: etc/cron.d/queerhaus
#     dest: /etc/cron.d/queerhaus

- name: Create matrix directory
  become: yes
  file:
    path: "{{ setups.matrix.run_dir }}"
    state: directory
    group: queers
    mode: "u=rwx,g=rwx,o=rx,g+s"

# - name: Install backup script
#   copy:
#     src: opt/queerhaus/collab/backup.sh
#     dest: /opt/queerhaus/collab/backup.sh
#     group: queers
#     mode: "u=rwx,g=rwx,o=rx"

- name: Create synapse media directory
  become: yes
  file:
    path: "{{ setups.matrix.data_dir }}/synapse/media_store"
    state: directory
    group: queers
    mode: "u=rwx,g=rwx,o=rxw"

- name: Create synapse config directory
  become: yes
  file:
    path: "{{ setups.matrix.run_dir }}/synapse"
    state: directory
    group: queers
    mode: "u=rwx,g=rwx,o=rx,g+s"

- name: Template synapse config
  become: yes
  template:
    src: homeserver.yaml
    dest: "{{ setups.matrix.run_dir }}/synapse/"
    group: queers
    mode: "u=rw,g=rw,o=r"

- name: Copy synapse signing key
  become: yes
  copy:
    src: queer.haus.signing.key
    dest: "{{ setups.matrix.run_dir }}/synapse/"
    group: queers
    mode: "u=rw,g=rw,o=r"

- name: Copy synapse log config
  become: yes
  copy:
    src: queer.haus.log.config
    dest: "{{ setups.matrix.run_dir }}/synapse/"
    group: queers
    mode: "u=rw,g=rw,o=r"

- name: Copy dendrite config files
  become: yes
  copy:
    src: dendrite/
    dest: "{{ setups.matrix.run_dir }}/dendrite/"
    group: queers
    mode: "u=rw,g=rw,o=r"

- name: Template dendrite config
  become: yes
  template:
    src: dendrite.yaml
    dest: "{{ setups.matrix.run_dir }}/dendrite/"
    group: queers
    mode: "u=rw,g=rw,o=r"

- name: Template element config
  become: yes
  template:
    src: element-config.json
    dest: "{{ setups.matrix.run_dir }}"
    group: queers
    mode: "u=rw,g=rw,o=r"

- name: Template docker compose
  become: yes
  template:
    src: docker-compose.yaml
    dest: "{{ setups.matrix.run_dir }}/docker-compose.yaml"
    group: queers
    mode: "u=rw,g=rw,o=r"

- name: Pull containers images (this will take time)
  command: 
    cmd: docker-compose pull
    chdir: "{{ setups.matrix.run_dir }}"
  register: pull_result
  changed_when: pull_result.stderr.find('downloaded newer image') != -1

- name: Start up containers (this can be slow)
  command: 
    cmd: docker-compose up -d --remove-orphans
    chdir: "{{ setups.matrix.run_dir }}"
  register: up_result
  changed_when: up_result.stderr.find('Creating') != -1 or up_result.stderr.find('Recreating') != -1
