---

# - name: Install cronjob
#   become: yes
#   copy:
#     src: etc/cron.d/queerhaus
#     dest: /etc/cron.d/queerhaus

- name: Create nextcloud directory
  file:
    path: "{{ setups.nextcloud.run_dir }}"
    state: directory
    group: queers
    mode: "u=rwx,g=rwx,o=rx,g+s"

# - name: Install backup script
#   copy:
#     src: opt/queerhaus/collab/backup.sh
#     dest: /opt/queerhaus/collab/backup.sh
#     group: queers
#     mode: "u=rwx,g=rwx,o=rx"

- name: Template docker compose
  template:
    src: docker-compose.yaml
    dest: "{{ setups.nextcloud.run_dir }}/docker-compose.yaml"
    group: queers
    mode: "u=rw,g=rw,o=r"

- name: Remove env file
  file:
    path: "{{ setups.nextcloud.run_dir }}/.env"
    state: absent

- name: Pull containers images (this will take time)
  command: 
    cmd: docker-compose pull
    chdir: "{{ setups.nextcloud.run_dir }}"
  register: pull_result
  changed_when: pull_result.stderr.find('downloaded newer image') != -1

- name: Start up containers (this can be slow)
  command: 
    cmd: docker-compose up -d --remove-orphans
    chdir: "{{ setups.nextcloud.run_dir }}"
  register: up_result
  changed_when: up_result.stderr.find('Creating') != -1 or up_result.stderr.find('Recreating') != -1
