version: '3.5'

networks:
  external_network:
    name: queerhaus_external
  internal_network:
    name: queerhaus_internal
    internal: true

services:

  traefik:
    image: traefik:2.2
    restart: unless-stopped
    command: 
      #- "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email={{ setups.traefik.config.email }}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - {{ setups.traefik.data_dir }}/letsencrypt:/letsencrypt
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: Host(`{{ inventory_hostname }}`)
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.tls.certresolver: letsencrypt
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.middlewares: dashboardauth
      traefik.http.middlewares.dashboardauth.basicauth.users: ${traefik_basic_auth}
    networks:
      - external_network

  # Global error page inspired from this: https://imandrea.me/blog/traefik-custom-404/
  error-pages:
    image: caddy:2-alpine
    restart: unless-stopped
    volumes:
      #- $PWD/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy:/usr/share/caddy
      - {{ setups.traefik.data_dir }}/caddy/data:/data
      - {{ setups.traefik.data_dir }}/caddy/config:/config
    labels:
      traefik.enable: true
      traefik.http.routers.error-router.rule: HostRegexp(`{host:.+}`)
      traefik.http.routers.error-router.priority: 1
      traefik.http.routers.error-router.entrypoints: websecure
      traefik.http.routers.error-router.tls.certresolver: letsencrypt
      traefik.http.routers.error-router.middlewares: error-middleware
      traefik.http.middlewares.error-middleware.errors.status: 400-599
      traefik.http.middlewares.error-middleware.errors.service: error-pages
      traefik.http.middlewares.error-middleware.errors.query: /index.html
      #traefik.http.middlewares.error-pages.errors.query: /{status}.html
      traefik.http.services.error-pages.loadbalancer.server.port: 80
    networks:
      - external_network
      - internal_network

